global:
  resolve_timeout: 5m
route:
  receiver: webhook_receiver
receivers:
  - name: webhook_receiver
    msteams_configs:
      - webhook_url_file: webhook_secret.txt
        send_resolved: true
        title: '{{ template "msteams.default.title" . }}'
        summary: '{{ template "msteams.default.summary" . }}'
        text: '{{ template "msteams.default.text" . }}'
