global:
  scrape_interval: 15s 
  evaluation_interval: 10s
rule_files:
  - 'rules.yml'
alerting:
  alertmanagers:
  - static_configs:
    - targets:
       - alertmanager:9093
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: simple_server
    static_configs:
      - targets: ["simple_go_server:8090"]
